#requires -Version 7.0
# Regression tests for Module 10 (audio.ingest). OS-portable: uses [IO.Path]::GetTempPath() and
# `Get-Command ffmpeg`, so the SAME harness runs on the cloud Linux box (ffmpeg 6.x, pre-ship gate)
# and on the Windows executor (ffmpeg 8.x). Fixtures are generated by ffmpeg itself (a 2 s stereo sine
# and a 1 s audio-less video) — no external asset. Verifies real conversions (codec/rate/channels via
# ffprobe, magic bytes, sha256), loudness modes, all error paths, and the Module 1 wrapper.
[CmdletBinding()]
param([string]$PwshPath = 'C:\Users\just_\.dotnet\tools\pwsh.exe')
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$moduleRoot = Split-Path -Parent $PSScriptRoot
$modulesDir = Split-Path -Parent $moduleRoot
Import-Module (Join-Path $modulesDir '01-skill-bootstrap/lib/SkillContract.psm1') -Force
$entry   = Join-Path $moduleRoot 'Invoke-AudioIngest.ps1'
$wrapper = Join-Path $modulesDir '01-skill-bootstrap/Invoke-Skill.ps1'
$script:fail = 0
function Check([string]$n, [bool]$c) { if ($c) { [Console]::Out.WriteLine("PASS  $n") } else { [Console]::Out.WriteLine("FAIL  $n"); $script:fail++ } }
function RunEntry([string[]]$a) {
    $prev = $ErrorActionPreference; $ErrorActionPreference = 'Continue'
    $o = & $PwshPath -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $entry @a
    $script:code = $LASTEXITCODE; $ErrorActionPreference = $prev
    return ([string]($o | Out-String)).Trim()
}
function Head([string]$p, [int]$n = 16) { try { $b = [System.IO.File]::ReadAllBytes($p); if ($b.Length -lt $n) { return $b }; return $b[0..($n-1)] } catch { return @() } }
function WavMagic([string]$p) { $b = Head $p 12; return ($b.Count -ge 12 -and $b[0] -eq 82 -and $b[1] -eq 73 -and $b[2] -eq 70 -and $b[3] -eq 70 -and $b[8] -eq 87 -and $b[9] -eq 65 -and $b[10] -eq 86 -and $b[11] -eq 69) }
function Mp3Magic([string]$p) { $b = Head $p 3; if ($b.Count -lt 3) { return $false }; if ($b[0] -eq 73 -and $b[1] -eq 68 -and $b[2] -eq 51) { return $true }; return ($b[0] -eq 255 -and ($b[1] -band 224) -eq 224) }
function FlacMagic([string]$p) { $b = Head $p 4; return ($b.Count -ge 4 -and $b[0] -eq 102 -and $b[1] -eq 76 -and $b[2] -eq 97 -and $b[3] -eq 67) }
function OggMagic([string]$p) { $b = Head $p 4; return ($b.Count -ge 4 -and $b[0] -eq 79 -and $b[1] -eq 103 -and $b[2] -eq 103 -and $b[3] -eq 83) }
function M4aMagic([string]$p) { $b = Head $p 8; return ($b.Count -ge 8 -and $b[4] -eq 102 -and $b[5] -eq 116 -and $b[6] -eq 121 -and $b[7] -eq 112) }

# ---- resolve ffmpeg for fixture generation (portable) ----
$ff = Get-Command 'ffmpeg' -CommandType Application -ErrorAction SilentlyContinue | Select-Object -First 1
Check 'ffmpeg available for fixtures' ($null -ne $ff)
if ($null -eq $ff) { [Console]::Out.WriteLine('cannot generate fixtures without ffmpeg'); [Console]::Out.WriteLine("$($script:fail) TEST(S) FAILED"); exit 1 }
$ffx = $ff.Source

# ---- manifest ----
$mv = Test-SkillManifest -Path (Join-Path $moduleRoot 'skill.json')
Check 'manifest validates' ([bool]$mv.valid)
if (-not $mv.valid) { $mv.errors | ForEach-Object { [Console]::Out.WriteLine("      - $_") } }

# ---- fixtures ----
$token = [Guid]::NewGuid().ToString('N').Substring(0,8)
$fxDir = Join-Path ([System.IO.Path]::GetTempPath()) "lo-audio-fx-$token"
New-Item -ItemType Directory -Path $fxDir -Force | Out-Null
$tone = Join-Path $fxDir 'tone_stereo_44100.wav'
$blank = Join-Path $fxDir 'blank_noaudio.mp4'
try {
    & $ffx -hide_banner -y -f lavfi -i 'sine=frequency=440:duration=2:sample_rate=44100' -ac 2 $tone *>$null
    & $ffx -hide_banner -y -f lavfi -i 'color=c=black:s=64x64:d=1' -an $blank *>$null
} catch { }
Check 'fixture tone.wav created' (Test-Path -LiteralPath $tone)
Check 'fixture blank.mp4 created' (Test-Path -LiteralPath $blank)

try {
    # ---- default ingest: tone(44100 stereo) -> wav 16k mono s16 ----
    $dTxt = RunEntry @('-InputFile', $tone)
    Check 'default exit 0' ($script:code -eq 0)
    $evd = Test-SkillResultEnvelope -Json $dTxt
    Check 'default envelope validates' ([bool]$evd.valid)
    if (-not $evd.valid) { $evd.errors | ForEach-Object { [Console]::Out.WriteLine("      - $_") } }
    $od = $dTxt | ConvertFrom-Json
    Check 'default status ok/partial' (@('ok','partial') -contains $od.status)
    Check 'default output file exists' ($null -ne $od.result -and (Test-Path -LiteralPath $od.result.output.path))
    Check 'default codec pcm_s16le' ($od.result.output.codec -eq 'pcm_s16le')
    Check 'default sample_rate 16000' ([int]$od.result.output.sample_rate -eq 16000)
    Check 'default channels 1' ([int]$od.result.output.channels -eq 1)
    Check 'default duration ~2s' ($null -ne $od.result.output.duration_s -and [double]$od.result.output.duration_s -ge 1.8 -and [double]$od.result.output.duration_s -le 2.3)
    Check 'default WAV magic' ((Test-Path -LiteralPath $od.result.output.path) -and (WavMagic $od.result.output.path))
    if (Test-Path -LiteralPath $od.result.output.path) {
        $bytes = [System.IO.File]::ReadAllBytes($od.result.output.path)
        $sha = ([System.BitConverter]::ToString(([System.Security.Cryptography.SHA256]::Create()).ComputeHash($bytes))).Replace('-','').ToLowerInvariant()
        Check 'default sha256 matches file' ($sha -eq $od.result.output.sha256)
    }
    Check 'default input probe present' ($null -ne $od.result.input.probe -and $od.result.input.audio_stream_present -eq $true)
    Check 'default argv recorded' ($null -ne $od.result.ffmpeg.argv -and @($od.result.ffmpeg.argv).Count -gt 0)

    # ---- format matrix ----
    $mp3 = RunEntry @('-InputFile', $tone, '-Format', 'mp3', '-Bitrate', '192k') | ConvertFrom-Json
    Check 'mp3 codec' ($mp3.result.output.codec -eq 'mp3')
    Check 'mp3 magic' ((Test-Path -LiteralPath $mp3.result.output.path) -and (Mp3Magic $mp3.result.output.path))

    $flac = RunEntry @('-InputFile', $tone, '-Format', 'flac') | ConvertFrom-Json
    Check 'flac codec' ($flac.result.output.codec -eq 'flac')
    Check 'flac magic' (FlacMagic $flac.result.output.path)

    $opus = RunEntry @('-InputFile', $tone, '-Format', 'opus') | ConvertFrom-Json
    Check 'opus codec' ($opus.result.output.codec -eq 'opus')
    Check 'opus OggS magic' (OggMagic $opus.result.output.path)

    $ogg = RunEntry @('-InputFile', $tone, '-Format', 'ogg') | ConvertFrom-Json
    Check 'ogg codec vorbis' ($ogg.result.output.codec -eq 'vorbis')
    Check 'ogg OggS magic' (OggMagic $ogg.result.output.path)

    $m4a = RunEntry @('-InputFile', $tone, '-Format', 'm4a') | ConvertFrom-Json
    Check 'm4a codec aac' ($m4a.result.output.codec -eq 'aac')
    Check 'm4a ftyp magic' (M4aMagic $m4a.result.output.path)

    # ---- keep-source rate/channels ----
    $keep = RunEntry @('-InputFile', $tone, '-Format', 'wav', '-SampleRate', '0', '-Channels', '0') | ConvertFrom-Json
    Check 'keep-source sample_rate 44100' ([int]$keep.result.output.sample_rate -eq 44100)
    Check 'keep-source channels 2' ([int]$keep.result.output.channels -eq 2)

    # ---- loudness: ebu ----
    $ebu = RunEntry @('-InputFile', $tone, '-Loudness', 'ebu') | ConvertFrom-Json
    Check 'ebu status ok/partial' (@('ok','partial') -contains $ebu.status)
    Check 'ebu mode reported' ($ebu.result.normalization.loudness.mode -eq 'ebu')
    Check 'ebu output exists' (Test-Path -LiteralPath $ebu.result.output.path)

    # ---- loudness: peak ----
    $peak = RunEntry @('-InputFile', $tone, '-Loudness', 'peak', '-PeakDb', '-1.0') | ConvertFrom-Json
    Check 'peak mode reported' ($peak.result.normalization.loudness.mode -eq 'peak')
    Check 'peak measured max volume' ($null -ne $peak.result.normalization.loudness.measured_max_volume_db)
    Check 'peak applied gain' ($null -ne $peak.result.normalization.loudness.applied_gain_db)
    Check 'peak output exists' (Test-Path -LiteralPath $peak.result.output.path)

    # ---- error paths (valid error envelopes, exit 0) ----
    $e1txt = RunEntry @('-InputFile', (Join-Path $fxDir 'does-not-exist.wav'))
    $ev1 = Test-SkillResultEnvelope -Json $e1txt
    $e1 = $e1txt | ConvertFrom-Json
    Check 'input_not_found valid envelope' ([bool]$ev1.valid)
    Check 'input_not_found error' ($e1.status -eq 'error' -and $e1.error.code -eq 'input_not_found')

    $e2 = RunEntry @('-InputFile', $tone, '-Format', 'xyz') | ConvertFrom-Json
    Check 'invalid_format error' ($e2.status -eq 'error' -and $e2.error.code -eq 'invalid_format')

    $e3 = RunEntry @('-InputFile', $tone, '-Channels', '3') | ConvertFrom-Json
    Check 'invalid_channels error' ($e3.status -eq 'error' -and $e3.error.code -eq 'invalid_channels')

    $e4txt = RunEntry @('-InputFile', $blank)
    $ev4 = Test-SkillResultEnvelope -Json $e4txt
    $e4 = $e4txt | ConvertFrom-Json
    Check 'no_audio_stream valid envelope' ([bool]$ev4.valid)
    Check 'no_audio_stream error' ($e4.status -eq 'error' -and $e4.error.code -eq 'no_audio_stream')

    $e5 = RunEntry @('-InputFile', $tone, '-FfmpegPath', (Join-Path $fxDir 'nope-ffmpeg.exe')) | ConvertFrom-Json
    Check 'ffmpeg_not_found error' ($e5.status -eq 'error' -and $e5.error.code -eq 'ffmpeg_not_found')

    # ---- wrapper (Module 1) — pass PwshPath through so it works on Linux + Windows ----
    $wjson = ([ordered]@{ input=$tone; format='wav'; sample_rate=16000; channels=1 } | ConvertTo-Json -Compress)
    $rep = & $PwshPath -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $wrapper -SkillDir $moduleRoot -InputsJson $wjson -PwshPath $PwshPath
    $repObj = ([string]($rep | Out-String)).Trim() | ConvertFrom-Json
    Check 'wrapper manifest_valid' ($repObj.manifest_valid -eq $true)
    Check 'wrapper envelope_valid' ($repObj.envelope_valid -eq $true)
}
finally {
    try { if (Test-Path -LiteralPath $fxDir) { Remove-Item -LiteralPath $fxDir -Recurse -Force -ErrorAction SilentlyContinue } } catch { }
}

if ($script:fail -eq 0) { [Console]::Out.WriteLine('ALL TESTS PASSED'); exit 0 } else { [Console]::Out.WriteLine("$($script:fail) TEST(S) FAILED"); exit 1 }
